language: objective-c

branches:
    only:
    - master

osx_image: xcode7.3
xcode_project: TDDTodo.xcodeproj
xcode_scheme: TDDTodoTests

script:
    - xcodebuild clean build test -project TDDTodo.xcodeproj -scheme TDDTodoTests CODE_SIGNING_REQUIRED=NO
