language: objective-c

branches:
    only:
    - master

osx_image: xcode7.3
xcode_project: TDDTodo.xcodeproj
xcode_scheme: TDDTodo
xcode_sdk: iphonesimulator9.3

script:
    - xcodebuild clean build test -project TDDTodo.xcodeproj -scheme TDDTodo CODE_SIGNING_REQUIRED=NO
