language: objective-c

branches:
    only:
    - master

osx_image: xcode7.3
xcode_project: TDDTodo.xcodeproj
xcode_scheme: TDDTodo
xcode_sdk: iphonesimulator9.3

script:
    - xctool -project TDDTodo.xcodeproj -scheme TDDTodoTests -sdk iphonesimulator CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
    - xctool test -project TDDTodo.xcodeproj -scheme TDDTodoTests -sdk iphonesimulator CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO

